const resources = {
  usuarios: {
    table: "USUARIOS",
    id: "id_usuario",
    publicFields: ["id_usuario", "nombre", "apellido", "dni", "email", "telefono", "fecha_registro", "administrador"],
    createFields: ["nombre", "apellido", "dni", "email", "telefono", "password", "fecha_registro", "administrador"],
    updateFields: ["nombre", "apellido", "dni", "email", "telefono", "password", "fecha_registro", "administrador"],
    adminOnly: true,
  },
  direcciones: {
    table: "DIRECCIONES_CLIENTE",
    id: "id_direccion",
    createFields: ["id_usuario", "calle", "altura", "piso_depto", "ciudad", "provincia", "codigo_postal", "indicaciones"],
    updateFields: ["id_usuario", "calle", "altura", "piso_depto", "ciudad", "provincia", "codigo_postal", "indicaciones"],
  },
  categorias: {
    table: "CATEGORIAS",
    id: "id_categoria",
    createFields: ["nombre", "descripcion"],
    updateFields: ["nombre", "descripcion"],
  },
  productos: {
    table: "PRODUCTOS",
    id: "id_producto",
    createFields: ["id_categoria", "nombre", "descripcion", "precio_base", "activo"],
    updateFields: ["id_categoria", "nombre", "descripcion", "precio_base", "activo"],
  },
  historialPrecios: {
    table: "HISTORIAL_PRECIOS",
    id: "id_precio",
    createFields: ["id_producto", "precio", "fecha_inicio", "fecha_fin"],
    updateFields: ["id_producto", "precio", "fecha_inicio", "fecha_fin"],
  },
  ofertas: {
    table: "OFERTAS",
    id: "id_oferta",
    createFields: ["nombre", "descripcion", "tipo_descuento", "valor_descuento", "fecha_inicio", "fecha_fin", "estado"],
    updateFields: ["nombre", "descripcion", "tipo_descuento", "valor_descuento", "fecha_inicio", "fecha_fin", "estado"],
  },
  ofertaProducto: {
    table: "OFERTA_PRODUCTO",
    compositeId: ["id_oferta", "id_producto"],
    createFields: ["id_oferta", "id_producto"],
    updateFields: [],
  },
  resenas: {
    table: "RESENAS",
    id: "id_resena",
    createFields: ["id_producto", "id_usuario", "calificacion", "comentario", "fecha"],
    updateFields: ["id_producto", "id_usuario", "calificacion", "comentario", "fecha"],
  },
  proveedores: {
    table: "PROVEEDORES",
    id: "id_proveedor",
    createFields: ["nombre_empresa", "telefono", "email", "direccion"],
    updateFields: ["nombre_empresa", "telefono", "email", "direccion"],
    adminOnly: true,
  },
  materiasPrimas: {
    table: "MATERIAS_PRIMAS",
    id: "id_materia_prima",
    createFields: ["nombre", "unidad_medida", "stock_actual", "stock_minimo"],
    updateFields: ["nombre", "unidad_medida", "stock_actual", "stock_minimo"],
    adminOnly: true,
  },
  comprasInsumos: {
    table: "COMPRAS_INSUMOS",
    id: "id_compra",
    createFields: ["id_proveedor", "id_materia_prima", "cantidad_comprada", "precio_total", "fecha_compra"],
    updateFields: ["id_proveedor", "id_materia_prima", "cantidad_comprada", "precio_total", "fecha_compra"],
    adminOnly: true,
  },
  recetasProductos: {
    table: "RECETAS_PRODUCTOS",
    compositeId: ["id_producto", "id_materia_prima"],
    createFields: ["id_producto", "id_materia_prima", "cantidad_necesaria"],
    updateFields: ["cantidad_necesaria"],
    adminOnly: true,
  },
  inventarioTerminados: {
    table: "INVENTARIO_TERMINADOS",
    id: "id_inventario",
    createFields: ["id_producto", "stock_actual", "stock_minimo"],
    updateFields: ["id_producto", "stock_actual", "stock_minimo"],
    adminOnly: true,
  },
  ordenesProduccion: {
    table: "ORDENES_PRODUCCION",
    id: "id_orden",
    createFields: ["id_producto", "cantidad_a_fabricar", "fecha_inicio", "fecha_fin_estimada", "estado"],
    updateFields: ["id_producto", "cantidad_a_fabricar", "fecha_inicio", "fecha_fin_estimada", "estado"],
    adminOnly: true,
  },
  carritos: {
    table: "CARRITO",
    id: "id_carrito",
    createFields: ["id_usuario", "fecha_creacion", "estado"],
    updateFields: ["id_usuario", "fecha_creacion", "estado"],
  },
  detalleCarrito: {
    table: "DETALLE_CARRITO",
    id: "id_detalle_carrito",
    createFields: ["id_carrito", "id_producto", "cantidad", "texto_personalizacion"],
    updateFields: ["id_carrito", "id_producto", "cantidad", "texto_personalizacion"],
  },
  pedidos: {
    table: "PEDIDOS",
    id: "id_pedido",
    createFields: ["id_usuario", "fecha_pedido", "monto_total", "estado_pedido"],
    updateFields: ["id_usuario", "fecha_pedido", "monto_total", "estado_pedido"],
  },
  detallePedido: {
    table: "DETALLE_PEDIDO",
    id: "id_detalle",
    createFields: ["id_pedido", "id_producto", "cantidad", "precio_unitario", "texto_personalizacion"],
    updateFields: ["id_pedido", "id_producto", "cantidad", "precio_unitario", "texto_personalizacion"],
  },
  metodosPago: {
    table: "METODOS_PAGO",
    id: "id_metodo_pago",
    createFields: ["nombre", "activo"],
    updateFields: ["nombre", "activo"],
  },
  pagos: {
    table: "PAGOS",
    id: "id_pago",
    createFields: ["id_pedido", "id_metodo_pago", "monto", "fecha_pago", "estado"],
    updateFields: ["id_pedido", "id_metodo_pago", "monto", "fecha_pago", "estado"],
  },
  cuotas: {
    table: "CUOTAS",
    id: "id_cuota",
    createFields: ["id_pago", "numero_cuota", "monto", "fecha_vencimiento", "estado"],
    updateFields: ["id_pago", "numero_cuota", "monto", "fecha_vencimiento", "estado"],
  },
  metodosEnvio: {
    table: "METODOS_ENVIO",
    id: "id_metodo_envio",
    createFields: ["nombre", "requiere_direccion"],
    updateFields: ["nombre", "requiere_direccion"],
  },
  envios: {
    table: "ENVIOS",
    id: "id_envio",
    createFields: ["id_pedido", "id_metodo_envio", "id_direccion", "costo_envio", "codigo_seguimiento", "fecha_despacho", "fecha_entrega", "estado_logistica"],
    updateFields: ["id_pedido", "id_metodo_envio", "id_direccion", "costo_envio", "codigo_seguimiento", "fecha_despacho", "fecha_entrega", "estado_logistica"],
  },
};

module.exports = resources;
